### ISSUE TITLE
大佬，这个插件大概哪个版本能够推出？

### ISSUE THREAD

**Issue by AugustTuan** [WingDr/siyuan-plugin-zettelkasten#1]
在线催更

**Comment by WingDr** [comment]
现在主要在看[这个问题](https://github.com/siyuan-note/siyuan/issues/9128)思源那边能不能解决

**Comment by AugustTuan** [comment]
> 现在主要在看[这个问题](https://github.com/siyuan-note/siyuan/issues/9128)思源那边能不能解决

更新了

**Comment by WingDr** [comment]
在做力

**Comment by WingDr** [comment]
草草上架了，目前只有新建卡片的功能，主体还在施工中，但是类似quickAdd的功能可以用了
