### ISSUE TITLE
无法设置快捷键

### ISSUE THREAD

**Issue by EdwardOwl** [WingDr/siyuan-plugin-zettelkasten#2]

**Comment by EdwardOwl** [comment]
0.01版本的插件，没有找到设置快捷键的地方。
使用快捷键插件查看，快速打开小窗的功能没有默认的快捷键。

**Comment by edward-kyle** [comment]
![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/ef100849-be15-4ec9-ab81-81ed8c3708ab)

**Comment by EdwardOwl** [comment]
![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/de743441-f44b-4ab6-986e-63accfe80a23)

**Comment by EdwardOwl** [comment]
![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/85ff04d3-7261-4f91-849c-d35309640b86)

**Comment by EdwardOwl** [comment]
![32c1a89dbe9e1a078b760f999c04f5c1](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/cdd7fdb6-fbe5-4c62-9aec-6367e8fc91d9)
在主菜单-快捷键界面找到了。

**Comment by WingDr** [comment]
ok
