### ISSUE TITLE
卡片小窗与工具栏plus插件冲突了

### ISSUE THREAD

**Issue by EdwardOwl** [WingDr/siyuan-plugin-zettelkasten#3]
![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/59d25576-26ad-4343-b3db-28663bddb8a3)
看图，工具栏挡住了一部分文字

**Comment by WingDr** [comment]
这个请去工具栏plus插件那边提issue，这个应该是由它来判断是否是窗口以及怎么样调整布局，我这没法做这方面的判断和调整
