### ISSUE TITLE
卡片小窗无法关闭

### ISSUE THREAD

**Issue by EdwardOwl** [WingDr/siyuan-plugin-zettelkasten#4]
似乎无法用相同的快捷键实现打开/关闭小窗。
另外，无法通过鼠标左键点击小窗的右上角的X进行关闭。
![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/9c41fcbd-ec89-4d44-b3e9-64645198d75f)

**Comment by EdwardOwl** [comment]
希望实现的效果：
快捷键按第一次：打开小窗A
编辑
快捷键按第二次：关闭小窗A
快捷键按第三次：打开小窗B
……
以此类推

**Comment by EdwardOwl** [comment]
不过，其他类似的卡片笔记小窗都是有一个发送按钮的。它们都是通过点击发送按钮，然后把你在小窗中编辑的文字发送到服务器后台，因此可以实现一个快捷键实现打开/关闭的效果。
![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/d70867c0-ed6c-4045-bf81-bb95c35065b2)
这是写拉松的卡片小窗

![image](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/47dfd243-5d58-443e-8150-67dcf5c177d6)
这是flomo的卡片小窗

**Comment by EdwardOwl** [comment]
> 不过，其他类似的卡片笔记小窗都是有一个发送按钮的。它们都是通过点击发送按钮，然后把你在小窗中编辑的文字发送到服务器后台，因此可以实现一个快捷键实现打开/关闭的效果。

如果要实现上面的这个想法，就会是：同一个快捷键有了打开并创建笔记、关闭笔记、再打开并创建另一个笔记。
不知道代码实现上可不可行

**Comment by WingDr** [comment]
> 似乎无法用相同的快捷键实现打开/关闭小窗。 另外，无法通过鼠标左键点击小窗的右上角的X进行关闭。 ![image](https://user-images.githubusercontent.com/78415230/269149705-9c41fcbd-ec89-4d44-b3e9-64645198d75f.png)

无法快捷键关闭是因为这个小窗本质上是一个新的思源进程，可以直接alt+F4关闭。点击关闭键没法关闭的情况能否在小窗按ctrl+shift+i打开控制台然后看下控制台输出？

**Comment by WingDr** [comment]
> > 不过，其他类似的卡片笔记小窗都是有一个发送按钮的。它们都是通过点击发送按钮，然后把你在小窗中编辑的文字发送到服务器后台，因此可以实现一个快捷键实现打开/关闭的效果。
> 
> 如果要实现上面的这个想法，就会是：同一个快捷键有了打开并创建笔记、关闭笔记、再打开并创建另一个笔记。 不知道代码实现上可不可行

主要是因为思源的架构，如果呈现一个纯文档的形式那就必须有一个现有的文档存在，所以不需要发送按钮，但是也会带来很多麻烦。用同一个快捷键关闭笔记相当于全局注册一个关闭窗口的快捷键，感觉挺没必要的（而且我也不太清楚怎么通过程序关闭一个前端的窗口

**Comment by EdwardOwl** [comment]
alt+f4、右上角x，均无法关闭

https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/78415230/839ee229-0877-42b0-ada6-5ae88ef18ec9

**Comment by AugustTuan** [comment]
这个插件quickadd 记录完笔记以后，发送的快捷键是啥

按alt+enter，enter好像都不太行

**Comment by WingDr** [comment]
> 这个插件quickadd 记录完笔记以后，发送的快捷键是啥
> 
> 按alt+enter，enter好像都不太行

如果输入了内容，直接关掉就可以了，右上角的叉甚至alt+f4都行，如果没有输入内容就关掉的话会自动把临时文档清除
