### ISSUE TITLE
希望手机端支持新建快速笔记

### ISSUE THREAD

**Issue by andyer1511** [WingDr/siyuan-plugin-zettelkasten#6]
在右拉菜单添加一个按钮，点击新建一个快速笔记。像下图的目录插件一样。
![Screenshot_20230920_182957_org b3log siyuan](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/18610532/fb6e0fc8-26e6-441a-887e-92e9fcd8ff10)

我现在是把日记格式设成这样`20060102150405`，把日记当快速笔记用的。电脑端按`Alt+5`，手机端点`日记`。
如果手机端也支持新建快速笔记，那日记就能回归日记本来的功能了。

**Comment by WingDr** [comment]
有个bug，本来设想的是可以的，今天de完一个bug然后再推个更新应该就ok了

**Comment by andyer1511** [comment]
好的，期待更新，这样思源笔记的桌面端快速记录功能也有了，手机端也算能用了。

**Comment by WingDr** [comment]
已经更新，可以试下有没有问题，理论上和桌面端是一样的

**Comment by andyer1511** [comment]
手机可以新建卡片了，现在还有一个小问题 #7
