### ISSUE TITLE
手机端快速笔记块标错位

### ISSUE THREAD

**Issue by andyer1511** [WingDr/siyuan-plugin-zettelkasten#7]
![Screenshot_20230922_143021_org b3log siyuan](https://github.com/WingDr/siyuan-plugin-zettelkasten/assets/18610532/7225aa62-b795-4fe7-8723-c2309459c2b8)

**Comment by WingDr** [comment]
这个跟V姐写的思源的底层有关（块标的定位问题），我是莫得办法的，可以去思源那边提一下，但是感觉影响不大（他们好像也不太愿意改这个）

**Comment by andyer1511** [comment]
好的，只要能新建卡片就好。
还有个关于卡片的文档名的问题，只保留日期时间观感上更好点。感觉后面的7 位随机字符没必要加上，而且作为文档名来说日期时间是够用的。

**Comment by WingDr** [comment]
> 好的，只要能新建卡片就好。 还有个关于卡片的文档名的问题，只保留日期时间观感上更好点。感觉后面的7 位随机字符没必要加上，而且作为文档名来说日期时间是够用的。

这个是偷懒用了思源的块id，之后会让能够在新建卡片的时候自己修改标题 #5

**Comment by andyer1511** [comment]
🆗
